"""initial schema

Revision ID: 127bd2bf0b5d
Revises: 
Create Date: 2026-04-09 18:47:07.331187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '127bd2bf0b5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS config")
    op.execute("CREATE SCHEMA IF NOT EXISTS data")
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_feeds_out', sa.Integer(), nullable=True),
    sa.Column('price_pln', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['auth.plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('feed_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('record_path', sa.String(length=512), nullable=True),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    op.create_table('feed_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_in_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('link_out', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['feed_in_id'], ['config.feed_in.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_out'),
    schema='config'
    )
    op.create_table('product_in',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feed_in_id', sa.Integer(), nullable=False),
    sa.Column('custom_product', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('product_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['feed_in_id'], ['config.feed_in.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('xml_element_in',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feed_in_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.Boolean(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('parent_path', sa.String(length=1024), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feed_in_id'], ['config.feed_in.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('xml_structure_out',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feed_out_id', sa.Integer(), nullable=False),
    sa.Column('sort_key', sa.String(length=50), nullable=False),
    sa.Column('custom_element', sa.Boolean(), nullable=False),
    sa.Column('path_in', sa.String(length=1024), nullable=True),
    sa.Column('level_out', sa.Integer(), nullable=False),
    sa.Column('path_out', sa.String(length=1024), nullable=False),
    sa.Column('parent_path_out', sa.String(length=1024), nullable=True),
    sa.Column('element_name_out', sa.String(length=255), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('attribute', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feed_out_id'], ['config.feed_out.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xml_structure_out', schema='data')
    op.drop_table('xml_element_in', schema='data')
    op.drop_table('product_in', schema='data')
    op.drop_table('feed_out', schema='config')
    op.drop_table('feed_in', schema='config')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('plans', schema='auth')
    op.execute("DROP SCHEMA IF EXISTS data")
    op.execute("DROP SCHEMA IF EXISTS config")
    op.execute("DROP SCHEMA IF EXISTS auth")
    # ### end Alembic commands ###
