"""add refresh_interval to feed_in

Revision ID: 5dc62ef81feb
Revises: 4eb11564563e
Create Date: 2026-04-09 19:52:57.967532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc62ef81feb'
down_revision: Union[str, None] = '4eb11564563e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.add_column('feed_in', sa.Column('refresh_interval', sa.Integer(), nullable=True), schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_in', 'refresh_interval', schema='config')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###
